

################################################################################
### Head: Keybind / Screenshot
##


#include ../keybind.m/Screenshot/*.conf


##
### Tail: Keybind / Screenshot
################################################################################




################################################################################
### Head: Keybind / Screenshot / ViaGrimshot
##


include ../keybind.m/Screenshot_ViaGrimshot/*.conf


##
### Tail: Keybind / Screenshot / ViaGrimshot
################################################################################
