<?php
################################################################################
### Head: Keybind / Screenshot
##


#include_once(__DIR__ . '/../keybind.m/Screenshot/Base.conf');

include_once(__DIR__ . '/../keybind.m/Screenshot/ViaGrimshot.conf');


##
### Tail: Keybind / Screenshot
################################################################################
?>
